version: "3.9"

services:

  backend:
    build: .

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      - postgres

  postgres:
    image: postgres:16

    restart: always

    environment:
      POSTGRES_DB: pco_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: