import { PERMISSIONS } from "../constants/permissions";

export const ADMIN_PERMISSIONS = [

  PERMISSIONS.PRODUCT_CREATE,
  PERMISSIONS.PRODUCT_UPDATE,
  PERMISSIONS.PRODUCT_DELETE,

  PERMISSIONS.ORDER_VIEW,
  PERMISSIONS.ORDER_UPDATE,

  PERMISSIONS.DASHBOARD_VIEW,

  PERMISSIONS.REPORT_VIEW,

  PERMISSIONS.USER_MANAGEMENT,

  PERMISSIONS.AUDIT_VIEW,

  PERMISSIONS.SETTINGS_MANAGEMENT

];