import { PERMISSIONS } from "../constants/permissions";

export const EXPORT_MANAGER_PERMISSIONS = [

  PERMISSIONS.RFQ_VIEW,
  PERMISSIONS.RFQ_APPROVE,

  PERMISSIONS.BULK_ORDER_VIEW,
  PERMISSIONS.BULK_ORDER_UPDATE,

  PERMISSIONS.REPORT_VIEW

];