export const AUDIT_ACTIONS = {

  RFQ_CREATED: "RFQ_CREATED",

  RFQ_CANCELLED: "RFQ_CANCELLED",

  RFQ_APPROVED: "RFQ_APPROVED",

  BULK_ORDER_CREATED: "BULK_ORDER_CREATED",

  BULK_ORDER_STATUS_UPDATED: "BULK_ORDER_STATUS_UPDATED",

  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",

  SHIPMENT_CREATED: "SHIPMENT_CREATED",

  EXPORT_INVOICE_GENERATED: "EXPORT_INVOICE_GENERATED",

  EXPORT_DOCUMENT_GENERATED: "EXPORT_DOCUMENT_GENERATED",

  LOGIN: "LOGIN",

  LOGOUT: "LOGOUT"

} as const;