export const PERMISSIONS = {

  // Product
  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  // Orders
  ORDER_VIEW: "ORDER_VIEW",
  ORDER_UPDATE: "ORDER_UPDATE",

  // RFQ
  RFQ_CREATE: "RFQ_CREATE",
  RFQ_VIEW: "RFQ_VIEW",
  RFQ_APPROVE: "RFQ_APPROVE",

  // Bulk Orders
  BULK_ORDER_VIEW: "BULK_ORDER_VIEW",
  BULK_ORDER_UPDATE: "BULK_ORDER_UPDATE",

  // Dashboard
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  // Reports
  REPORT_VIEW: "REPORT_VIEW",

  // Users
  USER_MANAGEMENT: "USER_MANAGEMENT",

  // Audit
  AUDIT_VIEW: "AUDIT_VIEW",

  // Settings
  SETTINGS_MANAGEMENT: "SETTINGS_MANAGEMENT"

} as const;