export const PERMISSIONS = {
  // Product
  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  // Inventory
INVENTORY_VIEW: "INVENTORY_VIEW",
INVENTORY_ADD_STOCK: "INVENTORY_ADD_STOCK",
INVENTORY_REMOVE_STOCK: "INVENTORY_REMOVE_STOCK",

 // Category
  CATEGORY_VIEW: "CATEGORY_VIEW",
  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_UPDATE: "CATEGORY_UPDATE",
  CATEGORY_DELETE: "CATEGORY_DELETE",

  // Supplier
  SUPPLIER_VIEW: "SUPPLIER_VIEW",
  SUPPLIER_CREATE: "SUPPLIER_CREATE",
  SUPPLIER_UPDATE: "SUPPLIER_UPDATE",
  SUPPLIER_DELETE: "SUPPLIER_DELETE",

  // Customer
  CUSTOMER_VIEW: "CUSTOMER_VIEW",
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
  CUSTOMER_DELETE: "CUSTOMER_DELETE",

  // Payment
  PAYMENT_VIEW: "PAYMENT_VIEW",
  PAYMENT_CREATE: "PAYMENT_CREATE",
  PAYMENT_UPDATE: "PAYMENT_UPDATE",
  PAYMENT_DELETE: "PAYMENT_DELETE",

  // Refund
  REFUND_VIEW: "REFUND_VIEW",
  REFUND_CREATE: "REFUND_CREATE",
  REFUND_UPDATE: "REFUND_UPDATE",
  REFUND_DELETE: "REFUND_DELETE",

  // Return
  RETURN_VIEW: "RETURN_VIEW",
  RETURN_CREATE: "RETURN_CREATE",
  RETURN_UPDATE: "RETURN_UPDATE",
  RETURN_DELETE: "RETURN_DELETE",

  // Orders
  ORDER_VIEW: "ORDER_VIEW",
  ORDER_UPDATE: "ORDER_UPDATE",

  // RFQ
  RFQ_CREATE: "RFQ_CREATE",
  RFQ_VIEW: "RFQ_VIEW",
  RFQ_APPROVE: "RFQ_APPROVE",

  // Bulk Orders
  BULK_ORDER_VIEW: "BULK_ORDER_VIEW",
  BULK_ORDER_UPDATE: "BULK_ORDER_UPDATE",
  BULK_ORDER_PAYMENT: "BULK_ORDER_PAYMENT",

  // Shipment
  SHIPMENT_VIEW: "SHIPMENT_VIEW",
  SHIPMENT_CREATE: "SHIPMENT_CREATE",
  SHIPMENT_UPDATE: "SHIPMENT_UPDATE",
  SHIPMENT_DELETE: "SHIPMENT_DELETE",

  // Invoice
  INVOICE_VIEW: "INVOICE_VIEW",

  // Dashboard
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  // Reports
  REPORT_VIEW: "REPORT_VIEW",

  // User
  USER_MANAGEMENT: "USER_MANAGEMENT",

  // Audit
  AUDIT_VIEW: "AUDIT_VIEW",

  // Settings
  SETTINGS_MANAGEMENT: "SETTINGS_MANAGEMENT",
} as const;

export type Permission =
  typeof PERMISSIONS[keyof typeof PERMISSIONS];