export const PERMISSIONS = {
  // Product
  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  // Orders
  ORDER_VIEW: "ORDER_VIEW",
  ORDER_UPDATE: "ORDER_UPDATE",

  // RFQ
  RFQ_CREATE: "RFQ_CREATE",
  RFQ_VIEW: "RFQ_VIEW",
  RFQ_APPROVE: "RFQ_APPROVE",

  // Bulk Orders
  BULK_ORDER_VIEW: "BULK_ORDER_VIEW",
  BULK_ORDER_UPDATE: "BULK_ORDER_UPDATE",
  BULK_ORDER_PAYMENT: "BULK_ORDER_PAYMENT",

  // Shipment
  SHIPMENT_VIEW: "SHIPMENT_VIEW",
  SHIPMENT_CREATE: "SHIPMENT_CREATE",
  SHIPMENT_UPDATE: "SHIPMENT_UPDATE",

  // Invoice
  INVOICE_VIEW: "INVOICE_VIEW",

  // Dashboard
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  // Reports
  REPORT_VIEW: "REPORT_VIEW",

  // User
  USER_MANAGEMENT: "USER_MANAGEMENT",

  // Audit
  AUDIT_VIEW: "AUDIT_VIEW",

  // Settings
  SETTINGS_MANAGEMENT: "SETTINGS_MANAGEMENT",
} as const;

export type Permission =
  typeof PERMISSIONS[keyof typeof PERMISSIONS];