import { ROLES } from "./roles";
import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {

  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.USER_MANAGEMENT,
    PERMISSIONS.AUDIT_VIEW,
  ],

  [ROLES.EXPORT_MANAGER]: [
    PERMISSIONS.RFQ_APPROVE,
    PERMISSIONS.BULK_ORDER_VIEW,
    PERMISSIONS.BULK_ORDER_UPDATE,
    PERMISSIONS.SHIPMENT_CREATE,
    PERMISSIONS.SHIPMENT_UPDATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.REPORT_VIEW,
  ],

  [ROLES.FINANCE]: [
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.REPORT_VIEW,
  ],

  [ROLES.WAREHOUSE_MANAGER]: [
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.BULK_ORDER_UPDATE,
    PERMISSIONS.SHIPMENT_VIEW,
    PERMISSIONS.INVOICE_VIEW,
  ],

  [ROLES.FARM_MANAGER]: [
    PERMISSIONS.PRODUCT_VIEW,
  ],

  [ROLES.BUYER]: [
    PERMISSIONS.RFQ_CREATE,
    PERMISSIONS.RFQ_VIEW,
    PERMISSIONS.BULK_ORDER_VIEW,
    PERMISSIONS.BULK_ORDER_PAYMENT,
    PERMISSIONS.SHIPMENT_VIEW,
    PERMISSIONS.INVOICE_VIEW,
  ],

  [ROLES.CUSTOMER]: [
    PERMISSIONS.PRODUCT_VIEW,
  ]

} as const;